### ISSUE TITLE
Estado del nido de mutantes

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/descarga_datos#15]
Será un placer ayudar en este PR
Abro Issue ✌

Hago referencia al tablero de Kanban:
[KANBAN GECI-23](https://app.gitkraken.com/glo/view/card/242b30d12c9b46c788c308b9020953da)

_Originally posted by @xwalls in https://github.com/IslasGECI/descarga_datos/pull/10#issuecomment-722691612_

**Comment by xwalls** [comment]
El dia de hoy se tuvo un tomate con @nepito para conocer el estado de anidación de los mutantes, conocer la estructura del código y dado que repito estuvo trabajando en este PR, me compartiera de su experiencia con los problemas actuales.

Hoy se logro:
- Identificar las zonas de anidación de los mutantes
- Posibles refactorizaciones
- Ideas de por donde actuar
- Resolución de dudas sobre el proyecto
- Conocer las técnicas ancestrales de @nepito sobre cacería en VS CODE

Fin del reporte. 🏹

**Comment by xwalls** [comment]
El dia de hoy se tuvieron dos tomates, con @nepito y @islasfernando para asistirme en la cacería de mutantes y para ayudar a nepito con el proyecto de `metadata_tools`, hicimos una prueba en conjunto y funciono perfectamente. llevándonos con ella 4 de 9 mutantes en el proyecto `descarga_datos`.

Hoy se logro:

- Más de una Consignación 🎉
- Posibles refactorizaciones
- Ideas de por donde actuar
- Resolución de dudas sobre el proyecto
- Conocer las técnicas ancestrales de @nepito sobre cacería en VS CODE

Fin del reporte. 🏹

**Comment by nepito** [comment]
[Aquí](https://github.com/IslasGECI/descarga_datos/commit/9cd9a28acb98c582373b4c4652079048aae61f71) ya no hay mutantes.
