### ISSUE TITLE
💥 El descarga_datos ignora el nombre de la carpeta en la que se encuentra el archivo que quiere descargar 💥

### ISSUE THREAD

**Issue by MaritzaB** [IslasGECI/descarga_datos#16]
Cuando queremos descargar dos archivos con el mismo nombre que se encuentran en carpetas diferentes, el `descarga_datos` no sabe cual es el archivo que tiene que descargar 🤦🏽.
[Por ejemplo](https://bitbucket.org/IslasGECI/muestreo-aves-marinas-ipbc/commits/0053ce830ac6cf656fdc62f8be321343cd33ff86) en la siguiente imagen pueden observar que queremos descargar el `datapackage.json` de dos bases de datos diferentes. El `descarga_datos` solo descarga un datapackage y si en el _Makefile_ cambiamos la dirección, descarga el mismo en las dos carpetas.

![image](https://user-images.githubusercontent.com/56838850/100394874-8d5a5d00-2ff3-11eb-8ddc-dbd849f5b653.png)

**Comment by devarops** [comment]
Relacionado (o duplicado) con #13

**Comment by devarops** [comment]
Resuelto en #17
