### ISSUE TITLE
Tal vez `File_Size_Getter` podría haber sido un mejor nombre.

### ISSUE THREAD

**Issue by nepito** [IslasGECI/descarga_datos#22]
Tal vez `File_Size_Getter` podría haber sido un mejor nombre.
Para la próxima que andemos por aquí.

- [ ] `getter_size_file` ➡️ `file_size_getter`.

_Originally posted by @devarops in https://github.com/IslasGECI/descarga_datos/pull/21#discussion_r840877740_

**Comment by devarops** [comment]
En lugar de:

```python
def get_file_size(file):
    getter_size_file = Getter_File_Size(file)
```

Tal vez:
```python
def get_file_size(file):
    file_size_getter = File_Size_Getter(file)
```

`getter_size_file` ➡️ `file_size_getter`.

**Comment by nepito** [comment]
[Aquí](https://github.com/IslasGECI/descarga_datos/commit/d659ead79feb1f4de591e9dd2e0f351894feacdd) atendimos este _issues_.
